package com.yrgo.dataaccess;

import com.yrgo.dataaccess.CallRowMapper;
import com.yrgo.dataaccess.CustomerDao;
import com.yrgo.dataaccess.CustomerRowMapper;
import com.yrgo.dataaccess.RecordNotFoundException;
import com.yrgo.domain.Call;
import com.yrgo.domain.Customer;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import javax.annotation.PostConstruct;
import java.util.ArrayList;
import java.util.List;
@Repository
public class CustomerDaoJdbcTemplateImpl implements CustomerDao {
    private static final String DELETE_SQL = "DELETE FROM CUSTOMER WHERE CUSTOMER_ID=?";
    private static final String UPDATE_SQL = "UPDATE CUSTOMER SET COMPANY_NAME=?, EMAIL=?, TELEPHONE=?,NOTES=? WHERE CUSTOMER_ID=?";
    private static final String INSERT_SQL = "INSERT INTO CUSTOMER (CUSTOMER_ID, COMPANY_NAME, NOTES) VALUES (?,?,?)";
    private static final String GET_ALL_CUSTOMERS_SQL = "SELECT CUSTOMER_ID, COMPANY_NAME, EMAIL, TELEPHONE, NOTES FROM CUSTOMER";
    private static final String CUSTOMER_DETAILS =  "SELECT CUSTOMER_ID, COMPANY_NAME, NOTES FROM CUSTOMER WHERE CUSTOMER_ID = ?";
    private static final String ADD_CALL =  "INSERT INTO TBL_CALL ( NOTES,CUSTOMER_ID) VALUES (?, ?)";
    private static final String GET_CALL = "SELECT NOTES, CUSTOMER_ID FROM TBL_CALL WHERE CUSTOMER_ID = ?";

    private JdbcTemplate template;
    @Autowired
    public CustomerDaoJdbcTemplateImpl(JdbcTemplate template) {
        this.template = template;
    }
    @PostConstruct
    private void createTables() {
        try {
            this.template.update(
                    "CREATE TABLE IF NOT EXISTS CUSTOMER (CUSTOMER_ID VARCHAR(50), COMPANY_NAME VARCHAR(255) NOT NULL, NOTES VARCHAR(500))"
            );
        } catch (org.springframework.jdbc.BadSqlGrammarException e) {
            System.out.println("Assuming the Customer table exists");
        }
        try {
            this.template.update(
                    "CREATE TABLE IF NOT EXISTS TBL_CALL (" +
                            "CALL_ID integer generated by default as identity (start with 1), " +
                            "NOTES VARCHAR(255), " +
                            "CUSTOMER_ID VARCHAR(50)) "

            );
        } catch (org.springframework.jdbc.BadSqlGrammarException e) {
            System.out.println("Assuming the Call table already exists.");
        }
    }

    @Override
    public void create(Customer customer) {
        template.update(INSERT_SQL,customer.getCustomerId(),customer.getCompanyName(),
                customer.getNotes());
    }

    @Override
    public Customer getById(String customerId) throws RecordNotFoundException {
        try {
            return template.queryForObject("select * from CUSTOMER where CUSTOMER_ID=?",new CustomerRowMapper(),customerId);
        } catch (EmptyResultDataAccessException e) {
            throw new RecordNotFoundException();
        }
    }

    @Override
    public List<Customer> getByName(String name) {
        List<Customer> list = template.query("select * from CUSTOMER where COMPANY_NAME=?",new CustomerRowMapper(),name);
        return list;
    }

    @Override
    public void update(Customer customerToUpdate) throws RecordNotFoundException {
        try{
            this.template.update(UPDATE_SQL,customerToUpdate.getCustomerId(),customerToUpdate.getCompanyName(),
                    customerToUpdate.getNotes() );
        }catch (EmptyResultDataAccessException e){
            throw new RecordNotFoundException();
        }
    }

    @Override
    public void delete(Customer oldCustomer) throws RecordNotFoundException {
        try{
            this.template.update(DELETE_SQL, oldCustomer.getCustomerId());
        }catch (EmptyResultDataAccessException e){
            throw new RecordNotFoundException();
        }
    }

    @Override
    public List<Customer> getAllCustomers() {
        return template.query(GET_ALL_CUSTOMERS_SQL, new CustomerRowMapper());
    }

    @Override
    public Customer getFullCustomerDetail(String customerId) throws RecordNotFoundException {
        try{
            Customer customer = template.queryForObject(CUSTOMER_DETAILS, new Object[]{customerId}, new CustomerRowMapper());
            List<Call> calls = template.query(GET_CALL, new Object[]{customerId}, new CallRowMapper());
            customer.setCalls(calls);
            return customer;
        }catch (EmptyResultDataAccessException e){
            throw new RecordNotFoundException();
        }
    }

    @Override
    public void addCall(Call newCall, String customerId) throws RecordNotFoundException {
        try{
            template.update(ADD_CALL, newCall.getNotes(), customerId);
        }catch (EmptyResultDataAccessException e){
            throw new RecordNotFoundException();
        }
    }
}
